#pragma once

// Stable Win32 RCDATA identifiers for the build-time-compiled D3D11 shaders.
// This header is consumed by both C++ and the generated resource script.
#define IDR_SYLC_NATIVE_VS                 100
#define IDR_SYLC_NATIVE_PS                 101

#define IDR_SYLC_SBS_VS                    110
#define IDR_SYLC_SBS_PS_LUMA               111
#define IDR_SYLC_SBS_PS_CHROMA             112

#define IDR_SYLC_SYNTH3D_VS_FULL           120
#define IDR_SYLC_SYNTH3D_PS_DEPTH_PREP      121
#define IDR_SYLC_SYNTH3D_PS_WARP_LUMA       122
#define IDR_SYLC_SYNTH3D_PS_WARP_CHROMA     123
#define IDR_SYLC_SYNTH3D_PS_DEPTH_VIEW_LUMA 124
#define IDR_SYLC_SYNTH3D_PS_DEPTH_VIEW_CHROMA 125
#define IDR_SYLC_SYNTH3D_PS_PLATE_ACCUM     126

#define IDR_SYLC_STEREO_LAB_PS_LUMA         127
#define IDR_SYLC_STEREO_LAB_PS_CHROMA       128
#define IDR_SYLC_STEREO_LAB_PS_METRICS      129
#define IDR_SYLC_STEREO_LAB_PS_PAIR_FIELD   130
#define IDR_SYLC_SYNTH3D_PS_PROVENANCE      131
#define IDR_SYLC_SYNTH3D_CS_OWNER_UNCERTAINTY 132
#define IDR_SYLC_SYNTH3D_CS_OWNER_DILATE      133
#define IDR_SYLC_SYNTH3D_CS_OWNER_LOCAL       134
#define IDR_SYLC_SYNTH3D_CS_OWNER_PROPAGATE   135
#define IDR_SYLC_SYNTH3D_CS_OWNER_COMPOSE     136
#define IDR_SYLC_SYNTH3D_CS_OWNER_SAFETY_TEMPORAL 137
